local M = {}

local palette = {
	bg = "#141216",
	bg_alt = "#100d10",
	bg_float = "#1a171c",
	bg_highlight = "#312623",
	bg_visual = "#3c2c33",
	border = "#2b2428",
	border_subtle = "#1d181b",
	comment = "#7d6b70",
	cursor = "#e38b5b",
	fg = "#eadfd7",
	fg_alt = "#cdbdb6",
	fg_muted = "#6f6468",
	white = "#f6eee8",
	teal = "#7bb5a3",
	green = "#8db27f",
	blue = "#7a9bc2",
	blue_bright = "#9dbce0",
	cyan = "#d2c0b1",
	cyan_alt = "#d7a18b",
	magenta = "#b089b9",
	magenta_bright = "#c5a2ce",
	gold = "#d7b06a",
	gold_bright = "#eac380",
	sand = "#c69b73",
	string = "#d9a066",
	string_alt = "#e28774",
	number = "#c9ba86",
	type = "#87a4b8",
	interface = "#a5bb9b",
	struct = "#b49ac4",
	function_name = "#d7b47a",
	error = "#e06a5f",
	diff_add = "#1f241c",
	diff_change = "#242730",
	diff_delete = "#2f1c1d",
	search = "#5c4730",
}

local function set_terminal_colors(p)
	vim.g.terminal_color_0 = p.bg_alt
	vim.g.terminal_color_1 = p.error
	vim.g.terminal_color_2 = p.green
	vim.g.terminal_color_3 = p.gold
	vim.g.terminal_color_4 = p.blue
	vim.g.terminal_color_5 = p.magenta
	vim.g.terminal_color_6 = p.teal
	vim.g.terminal_color_7 = p.fg_alt
	vim.g.terminal_color_8 = p.fg_muted
	vim.g.terminal_color_9 = p.error
	vim.g.terminal_color_10 = p.green
	vim.g.terminal_color_11 = p.gold_bright
	vim.g.terminal_color_12 = p.blue_bright
	vim.g.terminal_color_13 = p.magenta_bright
	vim.g.terminal_color_14 = p.teal
	vim.g.terminal_color_15 = p.fg
end

local function set_highlights(groups)
	for group, spec in pairs(groups) do
		vim.api.nvim_set_hl(0, group, spec)
	end
end

function M.apply()
	local p = palette

	vim.cmd("highlight clear")
	if vim.fn.exists("syntax_on") == 1 then
		vim.cmd("syntax reset")
	end

	vim.o.termguicolors = true
	vim.o.background = "dark"
	vim.g.colors_name = "ember_ink_dark"

	set_terminal_colors(p)

	set_highlights({
		ColorColumn = { bg = p.bg_float },
		Comment = { fg = p.comment, italic = true },
		Conceal = { fg = p.fg_muted },
		Constant = { fg = p.number },
		CurSearch = { fg = p.bg, bg = p.gold_bright },
		Cursor = { fg = p.bg, bg = p.cursor },
		CursorColumn = { bg = p.bg_float },
		CursorIM = { fg = p.bg, bg = p.cursor },
		CursorLine = { bg = p.bg_float },
		CursorLineNr = { fg = p.fg_alt, bold = true },
		Debug = { fg = p.error },
		Define = { fg = p.blue, italic = true },
		Delimiter = { fg = p.fg_muted },
		DiagnosticError = { fg = p.error },
		DiagnosticFloatingError = { fg = p.error, bg = p.bg_float },
		DiagnosticFloatingHint = { fg = p.teal, bg = p.bg_float },
		DiagnosticFloatingInfo = { fg = p.cursor, bg = p.bg_float },
		DiagnosticFloatingOk = { fg = p.green, bg = p.bg_float },
		DiagnosticFloatingWarn = { fg = p.gold, bg = p.bg_float },
		DiagnosticHint = { fg = p.teal },
		DiagnosticInfo = { fg = p.cursor },
		DiagnosticOk = { fg = p.green },
		DiagnosticSignError = { fg = p.error, bg = p.bg },
		DiagnosticSignHint = { fg = p.teal, bg = p.bg },
		DiagnosticSignInfo = { fg = p.cursor, bg = p.bg },
		DiagnosticSignOk = { fg = p.green, bg = p.bg },
		DiagnosticSignWarn = { fg = p.gold, bg = p.bg },
		DiagnosticUnderlineError = { sp = p.error, undercurl = true },
		DiagnosticUnderlineHint = { sp = p.teal, undercurl = true },
		DiagnosticUnderlineInfo = { sp = p.cursor, undercurl = true },
		DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
		DiagnosticUnderlineWarn = { sp = p.gold, undercurl = true },
		DiagnosticVirtualTextError = { fg = p.error, bg = p.bg_alt },
		DiagnosticVirtualTextHint = { fg = p.teal, bg = p.bg_alt },
		DiagnosticVirtualTextInfo = { fg = p.cursor, bg = p.bg_alt },
		DiagnosticVirtualTextOk = { fg = p.green, bg = p.bg_alt },
		DiagnosticVirtualTextWarn = { fg = p.gold, bg = p.bg_alt },
		DiagnosticWarn = { fg = p.gold },
		DiffAdd = { bg = p.diff_add },
		DiffChange = { bg = p.diff_change },
		DiffDelete = { bg = p.diff_delete },
		DiffText = { bg = p.bg_highlight },
		Directory = { fg = p.cursor },
		EndOfBuffer = { fg = p.bg },
		Error = { fg = p.error },
		ErrorMsg = { fg = p.error, bold = true },
		Exception = { fg = p.magenta },
		FloatBorder = { fg = p.border, bg = p.bg_float },
		FloatTitle = { fg = p.cursor, bg = p.bg_float, bold = true },
		FoldColumn = { fg = p.fg_muted, bg = p.bg },
		Folded = { fg = p.fg_alt, bg = p.bg_alt },
		Function = { fg = p.function_name },
		Identifier = { fg = p.fg },
		IncSearch = { fg = p.bg, bg = p.gold_bright },
		Include = { fg = p.blue, italic = true },
		Keyword = { fg = p.magenta, italic = true },
		Label = { fg = p.magenta },
		LineNr = { fg = p.fg_muted },
		LspCodeLens = { fg = p.fg_muted, italic = true },
		LspCodeLensSeparator = { fg = p.fg_muted },
		LspInlayHint = { fg = p.fg_muted, italic = true },
		LspReferenceRead = { bg = p.bg_highlight },
		LspReferenceText = { bg = p.bg_highlight },
		LspReferenceWrite = { bg = p.bg_highlight },
		Macro = { fg = p.blue, italic = true },
		MatchParen = { fg = p.cursor, bold = true, underline = true },
		ModeMsg = { fg = p.cursor, bold = true },
		MoreMsg = { fg = p.cursor },
		NonText = { fg = p.border },
		Normal = { fg = p.fg, bg = p.bg },
		NormalFloat = { fg = p.fg, bg = p.bg_float },
		NormalNC = { fg = p.fg, bg = p.bg },
		Number = { fg = p.number },
		Operator = { fg = p.magenta },
		Pmenu = { fg = p.fg, bg = p.bg_float },
		PmenuExtra = { fg = p.fg_alt, bg = p.bg_float },
		PmenuExtraSel = { fg = p.fg, bg = p.bg_highlight },
		PmenuKind = { fg = p.type, bg = p.bg_float },
		PmenuKindSel = { fg = p.type, bg = p.bg_highlight },
		PmenuMatch = { fg = p.cursor, bg = p.bg_float, bold = true },
		PmenuMatchSel = { fg = p.cursor, bg = p.bg_highlight, bold = true },
		PmenuSbar = { bg = p.border_subtle },
		PmenuSel = { fg = p.fg, bg = p.bg_highlight },
		PmenuThumb = { bg = p.fg_muted },
		PreCondit = { fg = p.blue, italic = true },
		PreProc = { fg = p.blue },
		Question = { fg = p.cursor },
		QuickFixLine = { bg = p.bg_highlight },
		Search = { bg = p.search },
		SignColumn = { bg = p.bg },
		Special = { fg = p.gold },
		SpecialChar = { fg = p.string_alt },
		SpecialComment = { fg = p.comment, italic = true },
		SpecialKey = { fg = p.fg_muted },
		SpellBad = { sp = p.error, undercurl = true },
		SpellCap = { sp = p.blue, undercurl = true },
		SpellLocal = { sp = p.teal, undercurl = true },
		SpellRare = { sp = p.magenta, undercurl = true },
		Statement = { fg = p.magenta, italic = true },
		StatusLine = { fg = p.fg_alt, bg = p.bg_alt },
		StatusLineNC = { fg = p.fg_muted, bg = p.bg_alt },
		StorageClass = { fg = p.blue },
		String = { fg = p.string },
		Structure = { fg = p.struct },
		Substitute = { fg = p.bg, bg = p.cursor },
		TabLine = { fg = p.fg_muted, bg = p.bg_alt },
		TabLineFill = { bg = p.bg_alt },
		TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
		Tag = { fg = p.blue },
		Title = { fg = p.cursor, bold = true },
		Todo = { fg = p.bg, bg = p.cursor, bold = true },
		Type = { fg = p.type },
		Typedef = { fg = p.type },
		Underlined = { fg = p.cursor, underline = true },
		Visual = { bg = p.bg_visual },
		VisualNOS = { bg = p.bg_visual },
		WarningMsg = { fg = p.gold, bold = true },
		Whitespace = { fg = p.border },
		WinBar = { fg = p.fg_alt, bg = p.bg },
		WinBarNC = { fg = p.fg_muted, bg = p.bg },
		WinSeparator = { fg = p.border_subtle, bg = p.bg },
		Boolean = { fg = p.number },
		Character = { fg = p.string },
		Conditional = { fg = p.magenta, italic = true },
		Float = { fg = p.number },
		Repeat = { fg = p.magenta, italic = true },
	})

	set_highlights({
		["@attribute"] = { fg = p.cyan_alt },
		["@attribute.builtin"] = { fg = p.cyan_alt, italic = true },
		["@boolean"] = { link = "Boolean" },
		["@comment"] = { link = "Comment" },
		["@comment.documentation"] = { link = "Comment" },
		["@constant"] = { fg = p.number },
		["@constant.builtin"] = { fg = p.blue, italic = true },
		["@constant.macro"] = { fg = p.blue, italic = true },
		["@constructor"] = { fg = p.type },
		["@diff.delta"] = { fg = p.teal },
		["@diff.minus"] = { fg = p.error },
		["@diff.plus"] = { fg = p.green },
		["@function"] = { fg = p.function_name },
		["@function.builtin"] = { fg = p.function_name, italic = true },
		["@function.call"] = { fg = p.function_name },
		["@function.method"] = { fg = p.function_name },
		["@function.method.call"] = { fg = p.function_name },
		["@function.macro"] = { fg = p.blue, italic = true },
		["@keyword"] = { fg = p.magenta, italic = true },
		["@keyword.conditional"] = { fg = p.magenta, italic = true },
		["@keyword.exception"] = { fg = p.magenta, italic = true },
		["@keyword.function"] = { fg = p.magenta, italic = true },
		["@keyword.import"] = { fg = p.blue, italic = true },
		["@keyword.operator"] = { fg = p.magenta },
		["@keyword.return"] = { fg = p.magenta, italic = true },
		["@label"] = { fg = p.magenta },
		["@markup.heading"] = { fg = p.blue, bold = true },
		["@markup.italic"] = { italic = true },
		["@markup.link"] = { fg = p.cursor, underline = true },
		["@markup.link.label"] = { fg = p.cyan_alt },
		["@markup.link.url"] = { fg = p.blue_bright, underline = true },
		["@markup.list"] = { fg = p.blue_bright },
		["@markup.raw"] = { fg = p.string },
		["@markup.strong"] = { bold = true },
		["@module"] = { fg = p.fg_alt },
		["@module.builtin"] = { fg = p.blue, italic = true },
		["@number"] = { fg = p.number },
		["@operator"] = { fg = p.magenta },
		["@property"] = { fg = p.cyan },
		["@punctuation.bracket"] = { fg = p.fg_muted },
		["@punctuation.delimiter"] = { fg = p.fg_muted },
		["@punctuation.special"] = { fg = p.gold },
		["@string"] = { fg = p.string },
		["@string.escape"] = { fg = p.sand },
		["@string.regex"] = { fg = p.string_alt },
		["@string.special"] = { fg = p.string },
		["@tag"] = { fg = p.blue },
		["@tag.attribute"] = { fg = p.cyan_alt },
		["@tag.delimiter"] = { fg = p.fg_muted },
		["@type"] = { fg = p.type },
		["@type.builtin"] = { fg = p.interface, italic = true },
		["@type.definition"] = { fg = p.type },
		["@variable"] = { fg = p.white },
		["@variable.builtin"] = { fg = p.blue, italic = true },
		["@variable.member"] = { fg = p.cyan },
		["@variable.parameter"] = { fg = p.interface, italic = true },
	})

	set_highlights({
		["@lsp.type.class"] = { link = "@type" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "@attribute" },
		["@lsp.type.enum"] = { fg = p.magenta },
		["@lsp.type.enumMember"] = { fg = p.magenta },
		["@lsp.type.function"] = { link = "@function" },
		["@lsp.type.interface"] = { fg = p.interface },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.macro"] = { link = "@function.macro" },
		["@lsp.type.method"] = { link = "@function.method" },
		["@lsp.type.namespace"] = { fg = p.fg_alt },
		["@lsp.type.number"] = { link = "@number" },
		["@lsp.type.operator"] = { link = "@operator" },
		["@lsp.type.parameter"] = { link = "@variable.parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.regexp"] = { link = "@string.regex" },
		["@lsp.type.string"] = { link = "@string" },
		["@lsp.type.struct"] = { fg = p.struct },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.typeParameter"] = { fg = p.interface, italic = true },
		["@lsp.type.variable"] = { link = "@variable" },
	})

	set_highlights({
		Added = { fg = p.green },
		BlinkCmpDoc = { fg = p.fg, bg = p.bg_float },
		BlinkCmpDocBorder = { fg = p.border, bg = p.bg_float },
		BlinkCmpKind = { fg = p.type, bg = p.bg_float },
		BlinkCmpKindSel = { fg = p.type, bg = p.bg_highlight },
		BlinkCmpLabel = { fg = p.fg, bg = p.bg_float },
		BlinkCmpLabelDeprecated = { fg = p.fg_muted, strikethrough = true },
		BlinkCmpLabelMatch = { fg = p.cursor, bg = p.bg_float, bold = true },
		BlinkCmpMenu = { fg = p.fg, bg = p.bg_float },
		BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_float },
		BlinkCmpMenuSelection = { fg = p.fg, bg = p.bg_highlight },
		BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg_float },
		BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg_float },
		DapUIBreakpointsCurrentLine = { fg = p.gold, bold = true },
		DapUIBreakpointsDisabledLine = { fg = p.fg_muted },
		DapUIBreakpointsInfo = { fg = p.teal },
		DapUIBreakpointsLine = { fg = p.gold },
		DapUIBreakpointsPath = { fg = p.cursor },
		DapUIDecoration = { fg = p.cursor },
		DapUIFloatBorder = { fg = p.border, bg = p.bg_float },
		DapUILineNumber = { fg = p.gold },
		DapUIModifiedValue = { fg = p.gold, bold = true },
		DapUIScope = { fg = p.cursor, bold = true },
		DapUISource = { fg = p.cyan_alt },
		DapUIStoppedThread = { fg = p.cursor, bold = true },
		DapUIThread = { fg = p.teal },
		DapUIType = { fg = p.type },
		DapUIValue = { fg = p.fg },
		DapUIVariable = { fg = p.white },
		DapUIWatchesEmpty = { fg = p.error },
		DapUIWatchesError = { fg = p.error },
		DapUIWatchesValue = { fg = p.teal },
		DiffviewCursorLine = { bg = p.bg_float },
		DiffviewFilePanelCounter = { fg = p.cursor },
		DiffviewFilePanelFileName = { fg = p.fg_alt },
		DiffviewFilePanelInsertions = { fg = p.green },
		DiffviewFilePanelDeletions = { fg = p.error },
		DiffviewFilePanelPath = { fg = p.fg_muted },
		DiffviewFilePanelRootPath = { fg = p.fg_muted },
		DiffviewFilePanelTitle = { fg = p.cursor, bold = true },
		DiffviewPrimary = { fg = p.cursor },
		DiffviewSecondary = { fg = p.teal },
		DiffviewStatusAdded = { fg = p.green },
		DiffviewStatusBroken = { fg = p.error },
		DiffviewStatusCopied = { fg = p.blue_bright },
		DiffviewStatusDeleted = { fg = p.error },
		DiffviewStatusIgnored = { fg = p.fg_muted },
		DiffviewStatusModified = { fg = p.teal },
		DiffviewStatusRenamed = { fg = p.blue },
		DiffviewStatusTypeChange = { fg = p.gold },
		DiffviewStatusUnmerged = { fg = p.magenta },
		DiffviewStatusUnknown = { fg = p.gold },
		DiffviewStatusUntracked = { fg = p.blue_bright },
		DiffviewWinSeparator = { fg = p.border_subtle, bg = p.bg },
		FidgetTask = { fg = p.fg_alt },
		FidgetTitle = { fg = p.cursor, bold = true },
		GitSignsAdd = { fg = p.green, bg = p.bg },
		GitSignsChange = { fg = p.teal, bg = p.bg },
		GitSignsDelete = { fg = p.error, bg = p.bg },
		GitSignsStagedAdd = { fg = p.green, bg = p.bg },
		GitSignsStagedChange = { fg = p.teal, bg = p.bg },
		GitSignsStagedDelete = { fg = p.error, bg = p.bg },
		MiniStatuslineDevinfo = { fg = p.fg_alt, bg = p.bg_alt },
		MiniStatuslineFileinfo = { fg = p.fg_alt, bg = p.bg_alt },
		MiniStatuslineFilename = { fg = p.fg, bg = p.bg_alt },
		MiniStatuslineInactive = { fg = p.fg_muted, bg = p.bg_alt },
		MiniStatuslineModeCommand = { fg = p.bg, bg = p.gold, bold = true },
		MiniStatuslineModeInsert = { fg = p.bg, bg = p.cursor, bold = true },
		MiniStatuslineModeNormal = { fg = p.bg, bg = p.blue, bold = true },
		MiniStatuslineModeOther = { fg = p.bg, bg = p.magenta, bold = true },
		MiniStatuslineModeReplace = { fg = p.bg, bg = p.error, bold = true },
		MiniStatuslineModeVisual = { fg = p.bg, bg = p.teal, bold = true },
		NeoTreeCursorLine = { bg = p.bg_float },
		NeoTreeDirectoryIcon = { fg = p.cursor },
		NeoTreeDirectoryName = { fg = p.cursor },
		NeoTreeDotfile = { fg = p.fg_muted },
		NeoTreeFileName = { fg = p.fg_alt },
		NeoTreeFileNameOpened = { fg = p.fg, bold = true },
		NeoTreeFloatBorder = { fg = p.border, bg = p.bg_alt },
		NeoTreeFloatTitle = { fg = p.cursor, bg = p.bg_alt, bold = true },
		NeoTreeGitAdded = { fg = p.green },
		NeoTreeGitConflict = { fg = p.magenta },
		NeoTreeGitDeleted = { fg = p.error },
		NeoTreeGitIgnored = { fg = p.fg_muted },
		NeoTreeGitModified = { fg = p.teal },
		NeoTreeGitUnstaged = { fg = p.gold },
		NeoTreeGitUntracked = { fg = p.blue_bright },
		NeoTreeIndentMarker = { fg = p.border },
		NeoTreeNormal = { fg = p.fg_alt, bg = p.bg_alt },
		NeoTreeNormalNC = { fg = p.fg_alt, bg = p.bg_alt },
		NeoTreeRootName = { fg = p.fg, bold = true },
		NeoTreeSymbolicLinkTarget = { fg = p.blue_bright, italic = true },
		NvimDapVirtualText = { fg = p.teal, bg = p.bg_alt, italic = true },
		NvimDapVirtualTextChanged = { fg = p.gold, bg = p.bg_alt, italic = true },
		NvimDapVirtualTextError = { fg = p.error, bg = p.bg_alt, italic = true },
		Removed = { fg = p.error },
		TelescopeBorder = { fg = p.border, bg = p.bg_float },
		TelescopeMatching = { fg = p.cursor, bold = true },
		TelescopeNormal = { fg = p.fg, bg = p.bg_float },
		TelescopePreviewBorder = { fg = p.border, bg = p.bg_float },
		TelescopePreviewTitle = { fg = p.bg, bg = p.teal, bold = true },
		TelescopePromptBorder = { fg = p.border, bg = p.bg_float },
		TelescopePromptNormal = { fg = p.fg, bg = p.bg_float },
		TelescopePromptPrefix = { fg = p.cursor, bg = p.bg_float },
		TelescopePromptTitle = { fg = p.bg, bg = p.cursor, bold = true },
		TelescopeResultsBorder = { fg = p.border, bg = p.bg_float },
		TelescopeResultsTitle = { fg = p.bg, bg = p.blue, bold = true },
		TelescopeSelection = { fg = p.fg, bg = p.bg_highlight },
		TelescopeSelectionCaret = { fg = p.cursor, bg = p.bg_highlight },
		TodoBgFIX = { fg = p.bg, bg = p.error, bold = true },
		TodoBgHACK = { fg = p.bg, bg = p.magenta, bold = true },
		TodoBgNOTE = { fg = p.bg, bg = p.cursor, bold = true },
		TodoBgPERF = { fg = p.bg, bg = p.type, bold = true },
		TodoBgTEST = { fg = p.bg, bg = p.blue, bold = true },
		TodoBgTODO = { fg = p.bg, bg = p.gold, bold = true },
		TodoBgWARN = { fg = p.bg, bg = p.gold, bold = true },
		TodoFgFIX = { fg = p.error },
		TodoFgHACK = { fg = p.magenta },
		TodoFgNOTE = { fg = p.cursor },
		TodoFgPERF = { fg = p.type },
		TodoFgTEST = { fg = p.blue },
		TodoFgTODO = { fg = p.gold },
		TodoFgWARN = { fg = p.gold },
		TodoSignFIX = { fg = p.error },
		TodoSignHACK = { fg = p.magenta },
		TodoSignNOTE = { fg = p.cursor },
		TodoSignPERF = { fg = p.type },
		TodoSignTEST = { fg = p.blue },
		TodoSignTODO = { fg = p.gold },
		TodoSignWARN = { fg = p.gold },
		WhichKey = { fg = p.cursor },
		WhichKeyBorder = { fg = p.border, bg = p.bg_float },
		WhichKeyDesc = { fg = p.fg },
		WhichKeyFloat = { bg = p.bg_float },
		WhichKeyGroup = { fg = p.blue_bright },
		WhichKeySeparator = { fg = p.fg_muted },
		WhichKeyValue = { fg = p.fg_muted },
	})
end

return M
